#!/bin/bash
echo ""
echo "================================================"
echo "  Kiro Gateway"
echo "================================================"
echo ""
echo "  Dashboard:  http://localhost:${PORT:-8000}"
echo "  API:        http://localhost:${PORT:-8000}/v1/chat/completions"
echo "  Models:     http://localhost:${PORT:-8000}/v1/models"
echo ""
echo "  API Key:    ${PROXY_API_KEY:-kiro-gateway-key}"
echo ""
echo "  Test:"
echo "    curl -H 'Authorization: Bearer ${PROXY_API_KEY:-kiro-gateway-key}' \\"
echo "      http://localhost:${PORT:-8000}/v1/models"
echo ""
echo "================================================"
