-- Soul Gateway SQLite schema (current tables only).
--
-- Conventions:
--   * Primary keys are TEXT UUIDs generated by the application (randomUUID).
--   * Encrypted secrets are BLOB columns; the runtime normalizes SQLite
--     Uint8Array values back to Node Buffer before decrypting.
--   * JSON documents/arrays are stored as TEXT validated with json_valid().
--     Array columns (e.g. models.tags) default to '[]'; object columns to '{}'.
--   * Booleans are stored as INTEGER 0/1 and normalized back to JS booleans.
--   * Timestamps are ISO-8601 UTC strings ('YYYY-MM-DDTHH:MM:SS.SSSZ') so that
--     application-supplied timestamps (new Date().toISOString()) and
--     database defaults sort and compare identically. Relative-time predicates
--     must compare against ISO values (strftime '%Y-%m-%dT%H:%M:%fZ' or a
--     JS-computed ISO cutoff), never the space-separated CURRENT_TIMESTAMP.
--
-- There is no Postgres schema, no separate database agent, and no historical
-- import path in the SQLite deployment. The cutover starts from an empty file.

PRAGMA foreign_keys = ON;

-- ── api_keys ────────────────────────────────────────────────────────
-- Signed-subject-only. Rows are deterministic, server-derived records for a
-- Ploinky-signed subject (agent:<repo>/<agent> or user:<userId>); they are
-- created on first valid signed request, never hold the plaintext key, and are
-- keyed uniquely by subject_id. There is no stored ciphertext: the bearer token
-- is `<subjectId>|<ed25519-signature>` and is verified against the Ploinky
-- public key on every request, so only the HMAC key_hash is persisted.
CREATE TABLE IF NOT EXISTS api_keys (
    id                    TEXT PRIMARY KEY,
    label                 TEXT NOT NULL,
    subject_id            TEXT NOT NULL UNIQUE,
    subject_type          TEXT NOT NULL CHECK (subject_type IN ('agent', 'user')),
    source                TEXT NOT NULL DEFAULT 'signed-subject' CHECK (source = 'signed-subject'),
    key_hash              BLOB NOT NULL UNIQUE,
    key_hint              TEXT NOT NULL,
    rpm_limit             INTEGER NOT NULL DEFAULT 60 CHECK (rpm_limit > 0),
    tpm_limit             INTEGER NOT NULL DEFAULT 100000 CHECK (tpm_limit > 0),
    daily_budget_usd      REAL,
    monthly_budget_usd    REAL,
    expires_at            TEXT,
    status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
    last_used_at          TEXT,
    metadata              TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    revoked_at            TEXT,
    CHECK (daily_budget_usd IS NULL OR daily_budget_usd >= 0),
    CHECK (monthly_budget_usd IS NULL OR monthly_budget_usd >= 0)
);

CREATE INDEX IF NOT EXISTS api_keys_status_expires_idx ON api_keys (status, expires_at);
CREATE INDEX IF NOT EXISTS api_keys_last_used_idx ON api_keys (last_used_at DESC);

-- ── providers ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS providers (
    id                     TEXT PRIMARY KEY,
    provider_key           TEXT NOT NULL UNIQUE,
    display_name           TEXT NOT NULL,
    kind                   TEXT NOT NULL CHECK (kind IN ('external_api', 'search', 'local_model', 'custom')),
    adapter_key            TEXT NOT NULL,
    auth_strategy          TEXT NOT NULL CHECK (auth_strategy IN ('none', 'api_key', 'oauth', 'hybrid', 'custom')),
    oauth_adapter_key      TEXT,
    base_url               TEXT,
    enabled                INTEGER NOT NULL DEFAULT 1,
    supports_streaming     INTEGER NOT NULL DEFAULT 1,
    supports_tools         INTEGER NOT NULL DEFAULT 1,
    supports_messages_api  INTEGER NOT NULL DEFAULT 0,
    supports_responses_api INTEGER NOT NULL DEFAULT 0,
    provider_mode          TEXT NOT NULL DEFAULT 'external_api' CHECK (provider_mode IN ('external_api', 'custom')),
    settings               TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(settings)),
    metadata               TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    created_at             TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at             TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK ((auth_strategy <> 'oauth') OR oauth_adapter_key IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS providers_enabled_kind_idx ON providers (enabled, kind);
CREATE INDEX IF NOT EXISTS providers_oauth_adapter_idx ON providers (oauth_adapter_key);

-- ── provider_accounts ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS provider_accounts (
    id                       TEXT PRIMARY KEY,
    provider_id              TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    account_label            TEXT NOT NULL,
    auth_type                TEXT NOT NULL CHECK (auth_type IN ('api_key', 'oauth')),
    status                   TEXT NOT NULL DEFAULT 'active'
                             CHECK (status IN ('active', 'refreshing', 'reauth_required', 'quota_exhausted', 'disabled', 'deleted')),
    external_account_id      TEXT,
    secret_ciphertext        BLOB,
    secret_iv                BLOB,
    secret_auth_tag          BLOB,
    secret_hint              TEXT,
    credentials_path         TEXT,
    access_token_expires_at  TEXT,
    refresh_token_expires_at TEXT,
    refresh_margin_seconds   INTEGER NOT NULL DEFAULT 300 CHECK (refresh_margin_seconds >= 0),
    quota_resets_at          TEXT,
    last_used_at             TEXT,
    last_error_type          TEXT,
    last_error_message       TEXT,
    last_error_at            TEXT,
    metadata                 TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    deleted_at               TEXT,
    CHECK (
        (auth_type = 'api_key' AND secret_ciphertext IS NOT NULL)
        OR (auth_type = 'oauth' AND credentials_path IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS provider_accounts_rotation_idx ON provider_accounts (provider_id, status, quota_resets_at);
CREATE INDEX IF NOT EXISTS provider_accounts_refresh_idx ON provider_accounts (provider_id, access_token_expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS provider_accounts_ext_id_unique_idx
    ON provider_accounts (provider_id, external_account_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS provider_accounts_lru_idx ON provider_accounts (last_used_at ASC);

-- ── models ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS models (
    id                       TEXT PRIMARY KEY,
    model_key                TEXT NOT NULL UNIQUE,
    display_name             TEXT NOT NULL,
    provider_id              TEXT REFERENCES providers(id) ON DELETE RESTRICT,
    provider_model_id        TEXT,
    execution_kind           TEXT,
    enabled                  INTEGER NOT NULL DEFAULT 1,
    concurrency_limit        INTEGER NOT NULL DEFAULT 3 CHECK (concurrency_limit > 0),
    queue_timeout_ms         INTEGER NOT NULL DEFAULT 60000 CHECK (queue_timeout_ms > 0),
    request_timeout_ms       INTEGER NOT NULL DEFAULT 120000 CHECK (request_timeout_ms > 0),
    pricing_mode             TEXT NOT NULL DEFAULT 'external_directory'
                             CHECK (pricing_mode IN ('external_directory', 'token', 'request', 'free')),
    input_price_per_million  REAL,
    output_price_per_million REAL,
    request_price_usd        REAL,
    rate_limit_override      TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(rate_limit_override)),
    budget_override          TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(budget_override)),
    loop_override            TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(loop_override)),
    response_filter_override TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(response_filter_override)),
    retry_policy             TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(retry_policy)),
    capabilities             TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(capabilities)),
    tags                     TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(tags)),
    is_free                  INTEGER NOT NULL DEFAULT 0,
    discovery_source         TEXT NOT NULL DEFAULT 'manual'
                             CHECK (discovery_source IN ('manual', 'auto_provisioned', 'synced')),
    strategy_kind            TEXT NOT NULL DEFAULT 'direct' CHECK (strategy_kind IN ('direct', 'cascade')),
    max_attempts             INTEGER,
    metadata                 TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    created_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at               TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (pricing_mode <> 'token' OR (input_price_per_million IS NOT NULL AND output_price_per_million IS NOT NULL)),
    CHECK (pricing_mode <> 'request' OR request_price_usd IS NOT NULL),
    CHECK (
        (strategy_kind = 'direct'  AND provider_id IS NOT NULL AND provider_model_id IS NOT NULL)
        OR
        (strategy_kind = 'cascade' AND provider_id IS NULL     AND provider_model_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS models_provider_enabled_idx ON models (provider_id, enabled);
CREATE INDEX IF NOT EXISTS models_enabled_kind_idx ON models (enabled, execution_kind);

-- ── model_aliases ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS model_aliases (
    id          TEXT PRIMARY KEY,
    alias       TEXT NOT NULL UNIQUE,
    model_id    TEXT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS model_aliases_model_idx ON model_aliases (model_id);

-- ── model_children (cascade child list) ─────────────────────────────
CREATE TABLE IF NOT EXISTS model_children (
    id                TEXT PRIMARY KEY,
    parent_model_id   TEXT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    child_model_id    TEXT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    priority          INTEGER NOT NULL CHECK (priority > 0),
    enabled           INTEGER NOT NULL DEFAULT 1,
    settings          TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(settings)),
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    UNIQUE (parent_model_id, child_model_id),
    UNIQUE (parent_model_id, priority),
    CHECK (parent_model_id <> child_model_id)
);

CREATE INDEX IF NOT EXISTS model_children_routing_idx ON model_children (parent_model_id, enabled, priority);
CREATE INDEX IF NOT EXISTS model_children_child_idx ON model_children (child_model_id);

-- ── middlewares ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS middlewares (
    id                TEXT PRIMARY KEY,
    middleware_key    TEXT NOT NULL UNIQUE,
    display_name      TEXT NOT NULL,
    source_type       TEXT NOT NULL CHECK (source_type IN ('builtin', 'custom')),
    module_path       TEXT NOT NULL,
    version           TEXT NOT NULL,
    checksum          TEXT NOT NULL,
    default_settings  TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(default_settings)),
    enabled           INTEGER NOT NULL DEFAULT 1,
    metadata          TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS middlewares_enabled_source_idx ON middlewares (enabled, source_type);

-- ── middleware_bindings (unified scope/target table) ────────────────
CREATE TABLE IF NOT EXISTS middleware_bindings (
    id              TEXT PRIMARY KEY,
    scope           TEXT NOT NULL CHECK (scope IN ('gateway', 'model', 'provider')),
    target_id       TEXT,
    middleware_key  TEXT NOT NULL,
    sort_order      INTEGER NOT NULL DEFAULT 100,
    enabled         INTEGER NOT NULL DEFAULT 1,
    settings        TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(settings)),
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    CHECK (
        (scope = 'gateway' AND target_id IS NULL)
        OR
        (scope IN ('model', 'provider') AND target_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS middleware_bindings_scope_enabled_idx ON middleware_bindings (scope, enabled, sort_order);
CREATE INDEX IF NOT EXISTS middleware_bindings_target_idx ON middleware_bindings (target_id, scope, enabled, sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS middleware_bindings_gateway_unique_idx
    ON middleware_bindings (middleware_key) WHERE scope = 'gateway';
CREATE UNIQUE INDEX IF NOT EXISTS middleware_bindings_model_unique_idx
    ON middleware_bindings (target_id, middleware_key) WHERE scope = 'model';
CREATE UNIQUE INDEX IF NOT EXISTS middleware_bindings_provider_unique_idx
    ON middleware_bindings (target_id, middleware_key) WHERE scope = 'provider';

-- ── blacklist_rules ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS blacklist_rules (
    id              TEXT PRIMARY KEY,
    rule_key        TEXT NOT NULL UNIQUE,
    description     TEXT NOT NULL,
    match_type      TEXT NOT NULL CHECK (match_type IN ('exact', 'substring', 'regex')),
    pattern         TEXT NOT NULL,
    case_sensitive  INTEGER NOT NULL DEFAULT 0,
    priority        INTEGER NOT NULL DEFAULT 100,
    enabled         INTEGER NOT NULL DEFAULT 1,
    metadata        TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS blacklist_rules_eval_idx ON blacklist_rules (enabled, priority, match_type);

-- ── model_cooldowns ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS model_cooldowns (
    id                 TEXT PRIMARY KEY,
    model_id           TEXT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    source_account_id  TEXT REFERENCES provider_accounts(id) ON DELETE SET NULL,
    request_id         TEXT,
    reason_type        TEXT NOT NULL,
    reason_message     TEXT,
    started_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    expires_at         TEXT NOT NULL,
    cleared_at         TEXT,
    cleared_by         TEXT,
    metadata           TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    CHECK (expires_at > started_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS model_cooldowns_active_unique_idx ON model_cooldowns (model_id) WHERE cleared_at IS NULL;
CREATE INDEX IF NOT EXISTS model_cooldowns_expires_idx ON model_cooldowns (expires_at);
CREATE INDEX IF NOT EXISTS model_cooldowns_reason_idx ON model_cooldowns (reason_type, cleared_at);

-- ── sessions ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sessions (
    id                   TEXT PRIMARY KEY,
    group_key            TEXT NOT NULL,
    group_display        TEXT NOT NULL,
    sequence_no          INTEGER NOT NULL CHECK (sequence_no > 0),
    api_key_id           TEXT NOT NULL REFERENCES api_keys(id) ON DELETE RESTRICT,
    soul_id              TEXT,
    agent_name           TEXT NOT NULL,
    explicit_session_id  TEXT,
    status               TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
    started_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    last_activity_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    ended_at             TEXT,
    request_count        INTEGER NOT NULL DEFAULT 0,
    input_tokens_total   INTEGER NOT NULL DEFAULT 0,
    output_tokens_total  INTEGER NOT NULL DEFAULT 0,
    metadata             TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    UNIQUE (group_key, sequence_no)
);

CREATE INDEX IF NOT EXISTS sessions_implicit_lookup_idx ON sessions (api_key_id, agent_name, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS sessions_soul_idx ON sessions (soul_id, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS sessions_status_idx ON sessions (status, last_activity_at DESC);

-- ── session_state ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS session_state (
    session_id             TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
    summary_text           TEXT NOT NULL DEFAULT '',
    facts_json             TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(facts_json)),
    recent_fingerprints    TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(recent_fingerprints)),
    recent_similarity      TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(recent_similarity)),
    recent_token_volume    INTEGER NOT NULL DEFAULT 0,
    response_count         INTEGER NOT NULL DEFAULT 0,
    last_response_at       TEXT,
    last_loop_detected_at  TEXT,
    updated_at             TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS session_state_updated_idx ON session_state (updated_at DESC);

-- ── audit_logs (single indexed table; retention deletes old rows) ────
CREATE TABLE IF NOT EXISTS audit_logs (
    log_id                TEXT NOT NULL,
    started_at            TEXT NOT NULL,
    request_id            TEXT NOT NULL,
    request_format        TEXT NOT NULL CHECK (request_format IN ('openai_chat', 'anthropic_messages', 'openai_responses')),
    status                TEXT NOT NULL CHECK (status IN ('in_progress', 'succeeded', 'failed', 'aborted')),
    api_key_id            TEXT NOT NULL,
    soul_id               TEXT,
    agent_name            TEXT,
    user_agent            TEXT,
    session_id            TEXT,
    requested_model       TEXT NOT NULL,
    resolved_model_id     TEXT,
    resolved_provider_id  TEXT,
    tier_id               TEXT,
    provider_account_id   TEXT,
    http_status           INTEGER,
    error_type            TEXT,
    error_message         TEXT,
    retryable             INTEGER,
    cascaded              INTEGER NOT NULL DEFAULT 0,
    cache_hit             INTEGER NOT NULL DEFAULT 0,
    blocked               INTEGER NOT NULL DEFAULT 0,
    loop_detected         INTEGER NOT NULL DEFAULT 0,
    truncated             INTEGER NOT NULL DEFAULT 0,
    slow                  INTEGER NOT NULL DEFAULT 0,
    oversized             INTEGER NOT NULL DEFAULT 0,
    streaming             INTEGER NOT NULL DEFAULT 0,
    queue_wait_ms         INTEGER,
    latency_ms            INTEGER,
    ttfb_ms               INTEGER,
    completed_at          TEXT,
    attempt_count         INTEGER NOT NULL DEFAULT 0,
    retry_trace           TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(retry_trace)),
    middleware_trace      TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(middleware_trace)),
    request_headers       TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(request_headers)),
    request_payload       TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(request_payload)),
    response_payload      TEXT,
    response_excerpt      TEXT,
    response_fingerprint  TEXT,
    input_tokens          INTEGER,
    output_tokens         INTEGER,
    total_tokens          INTEGER,
    input_cost_usd        REAL NOT NULL DEFAULT 0,
    output_cost_usd       REAL NOT NULL DEFAULT 0,
    total_cost_usd        REAL NOT NULL DEFAULT 0,
    budget_exempt         INTEGER NOT NULL DEFAULT 0,
    flags                 TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(flags)),
    metadata              TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(metadata)),
    PRIMARY KEY (started_at, log_id)
);

CREATE INDEX IF NOT EXISTS audit_logs_request_id_idx ON audit_logs (request_id);
CREATE INDEX IF NOT EXISTS audit_logs_api_key_started_idx ON audit_logs (api_key_id, started_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_soul_started_idx ON audit_logs (soul_id, started_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_agent_started_idx ON audit_logs (agent_name, started_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_requested_model_started_idx ON audit_logs (requested_model, started_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_status_started_idx ON audit_logs (status, started_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_error_started_idx ON audit_logs (error_type, started_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_session_started_idx ON audit_logs (session_id, started_at DESC);
